;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        backward-sexp
        beginning-of-buffer
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-star
        comint-delchar-or-maybe-eof
        comment-dwim
        compile
        consult-buffer
        electric-pair-delete-pair
        emojify-delete-emoji-backward
        end-of-buffer
        forward-sexp
        indent-for-tab-command
        kill-region
        lsp-signature-stop
        lsp-ui-doc--handle-mouse-movement
        mc--insert-number-and-increase
        mc/mark-next-lines
        mode-line-other-buffer
        org-beginning-of-line
        org-delete-char
        org-edit-src-save
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-delete-char
        sp-forward-sexp
        sp-kill-region
        sp-kill-word
        sp-remove-active-pair-overlay
        sp-unwrap-sexp
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-semi&comma
        ))
