;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	beginning-of-buffer
	comint-delchar-or-maybe-eof
	electric-pair-delete-pair
	emojify-delete-emoji-backward
	end-of-buffer
	forward-sexp
	indent-for-tab-command
	kill-region
	lsp-signature-stop
	mc/mark-next-lines
	org-beginning-of-line
	org-delete-char
	org-edit-src-save
	org-end-of-line
	org-force-self-insert
	org-kill-line
	org-self-insert-command
	sp-backward-delete-char
	sp-backward-kill-word
	sp-delete-char
	sp-forward-sexp
	sp-kill-region
	sp-kill-word
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	))
