;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-kill-line
	org-return-and-maybe-indent
	org-self-insert-command
	sp-backward-delete-char
	sp-delete-char
	sp-kill-region
	))

(setq mc/cmds-to-run-once
      '(
	))
